# Generated by Django 4.2.4 on 2023-08-29 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_or_ean', models.CharField(max_length=200)),
                ('how_many_offers', models.IntegerField(blank=True, null=True)),
                ('offer_link', models.TextField(blank=True, null=True)),
                ('best_title', models.TextField(blank=True, null=True)),
                ('max_howManyBought', models.IntegerField(blank=True, null=True)),
                ('best_price', models.FloatField(blank=True, null=True)),
                ('lowest_price', models.FloatField(blank=True, null=True)),
                ('highest_price', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('best_offer_link', models.TextField(blank=True, null=True)),
                ('best_description', models.TextField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('photos_links', models.TextField(blank=True, null=True)),
                ('first_photo_link', models.TextField(blank=True, null=True)),
                ('product_category', models.TextField(blank=True, null=True)),
                ('product_category_id', models.TextField(blank=True, null=True)),
                ('howManyBought', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(default=datetime.datetime.now)),
                ('best_offer_owner', models.CharField(blank=True, max_length=200, null=True)),
                ('best_offer_delivery_costs', models.CharField(blank=True, max_length=200, null=True)),
                ('product_rating', models.CharField(blank=True, max_length=200, null=True)),
                ('product_opinions', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
