# Generated by Django 4.2.4 on 2023-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_or_ean', models.CharField(max_length=200)),
                ('offer_link', models.TextField(blank=True, null=True)),
                ('best_title', models.TextField(blank=True)),
                ('max_howManyBought', models.FloatField(blank=True, null=True)),
                ('best_price', models.FloatField(blank=True, null=True)),
                ('lowest_price', models.FloatField(blank=True, null=True)),
                ('highest_price', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('best_offer_price', models.FloatField(blank=True, null=True)),
                ('best_description', models.TextField(blank=True)),
                ('parameters', models.TextField(blank=True)),
                ('photos_links', models.TextField(blank=True)),
            ],
        ),
    ]
