# Generated by Django 4.2.4 on 2023-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='best_offer_price',
        ),
        migrations.AddField(
            model_name='products',
            name='best_offer_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
