# Generated by Django 4.2.4 on 2023-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0003_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.TextField(blank=True),
        ),
    ]
