# Generated by Django 4.2.4 on 2023-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0005_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_photo_link',
            field=models.TextField(blank=True),
        ),
    ]
