# Generated by Django 4.2.4 on 2023-08-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0006_product_first_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_howManyBought',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
