# Generated by Django 4.2.4 on 2023-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0008_product_how_many_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_photo_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
