# Generated by Django 4.2.4 on 2023-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0009_alter_product_best_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='howManyBought',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
