# Generated by Django 4.2.4 on 2023-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0010_product_howmanybought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
