# Generated by Django 4.2.4 on 2023-08-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0012_product_best_offer_delivery_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
